name: LisaRidley
favicon: null
layout_spectrum: 0.58037
typography_spectrum: 0.66193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dcdcdc'
    - '#7c7c7c'
    - '#c0c0c0'
    - '#054370'
  brandStrength: 0.7727082965429872
  lightness: 0.4375
  saturation: 0.10305365663953125
  rhythmicContrast: 0.25
purpose: []
